# Generated by Django 5.2.1 on 2025-05-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_image_cloudinary_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='details',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
