# Generated by Django 5.2.1 on 2025-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_details_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='details',
            field=models.CharField(max_length=10000),
        ),
    ]
