# Generated by Django 5.2.1 on 2025-05-23 13:53

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
