# Generated by Django 5.2.1 on 2025-05-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_description_alter_review_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image_cloudinary',
        ),
    ]
