# Generated by Django 5.2.1 on 2025-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_review_image_remove_review_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='details',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
