# Generated by Django 5.2.1 on 2025-05-21 09:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='details',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='title',
        ),
        migrations.AddField(
            model_name='reservation',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 9, 23, 45, 963253, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(default='Unknown Guest', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.roomtype'),
        ),
    ]
