# Generated by Django 5.2.1 on 2025-05-23 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_room_type_alter_roomtype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('family', 'Family')], on_delete=django.db.models.deletion.CASCADE, to='reservation.roomtype'),
        ),
    ]
