# Generated by Django 5.2.1 on 2025-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('DELUXE', 'Deluxe'), ('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('FAMILY', 'Family'), ('SUITE', 'Suite')]),
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
