# Generated by Django 5.2.1 on 2025-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('DELUXE', 'Deluxe'), ('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('FAMILY', 'Family'), ('SUITE', 'Suite')], max_length=20),
        ),
    ]
