# Generated by Django 5.2.1 on 2025-05-28 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
